[package]
name = "poker"
version = "0.1.0"
authors = ["bedna <bedna.bedna@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
rayon = "1.5"
argh = "0.1.4"